Homework 5 completed
Sapphireexe/JS_HW_old pull request #3
Opened 2024-06-06 00:42 UTC by Sapphireexe

Finally completed that task with triangle and rhombus.

Every task in hw_5_1 finished.

Every task in hw_5_2 finished.

Every task in hw_5_3 finished.

2024-06-06 01:03 UTC, anatoly-karpovich requested changes

2024-06-06 01:03 UTC, anatoly-karpovich commented on HW_5/hw_5_1.js
> +};
```suggestion
let outputString = ':)';
let result = '';

for (let i = 0; i < 5; i++) {
    result += outputString;
    console.log(result);   
};
```
With this implementation you can privide any other symbol without changing task logics

2024-06-06 01:03 UTC, anatoly-karpovich commented on HW_5/hw_5_1.js
> +    console.log(':)'.repeat(i));
Same, use variable for a smile

2024-06-06 01:03 UTC, anatoly-karpovich commented on HW_5/hw_5_1.js
> +    console.log(':)'.repeat(iteration+1));
Once again)

2024-06-06 01:03 UTC, anatoly-karpovich commented on HW_5/hw_5_2.js
> +  if (isNaN(a)) {
Here we use only numbers, so just check for typeof number

2024-06-06 01:03 UTC, anatoly-karpovich commented on HW_5/hw_5_2.js
> +  if (a < byte) { // bytes
Where did you l lose the while loop?)

2024-06-06 01:03 UTC, anatoly-karpovich commented on HW_5/hw_5_2.js
> +    return 'Error. Invalid input data.';
```suggestion
    throw new Error("Invalid input data.");
```

2024-06-06 01:03 UTC, anatoly-karpovich commented on HW_5/hw_5_3.js
> +    return `Invalid input string. Must contain word only.`
```suggestion
    throw new Error(`Invalid input string. Must contain word only.`)
```

2024-06-06 01:03 UTC, anatoly-karpovich commented on HW_5/hw_5_3.js
> +    return `Invalid input string. Must contain word only.`
Same logic for errors as above

2024-06-08 14:12 UTC, Sapphireexe commented
Made changes to the task according to the notes

2024-06-09 12:43 UTC, anatoly-karpovich approved these changes, later dismissed

2024-06-09 15:05 UTC, VladimirLQA approved these changes, later dismissed

2024-06-10 07:12 UTC, Sapphireexe commented
Force-merged hw_5 into main because of two MR conflicts. Will be more attentive.

2024-06-10 07:12 UTC, merged